<?php

########################################################################
# Extension Manager/Repository config file for ext: "leonex_template"
#
# Auto generated by Extension Builder 2012-01-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Leonex TYPO3 Template',
	'description' => 'TYPO3 template for Leonex webpages.',
	'category' => 'templates',
	'author' => '',
	'author_email' => '',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'automaketemplate' => '',
			'dd_googlesitemap' => '',
			'formhandler' => '',
			'realurl' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
				'tt_news' => '',
				'macina_searchbox' => '',
				'rlmp_language_detection' => '',
				'static_info_tables' => '',
				'sr_feuser_register' => '',
				'sr_email_subscribe' => '',
				'a21glossary' => '',
				'tt_address' => '',
		),
	),
);

?>
